### ISSUE TITLE
Need improve for big practice (part 1)

### ISSUE THREAD

**Issue by hungle-agilityio** [ngocquang2509/Javascript-Training#5]
- Issues about structure:
  + Need remove `test.http` and `main.js`, I don't think we need it.
  + Missing files: `README.md` and `.editorconfig`
- `.gitignore` you should just ignore files that exist in the project, you added too many unused files.
- Please create and update `README.md`, it seems to be required when you start the practices/projects, everyone can know a lot of information about your practice as well as how to setup and run. 
- You should create a `scripts` or `js` folder and create `.js` files inside it such as `model.js, controler.js, view.js`etc. You can split subfolders to suit your practice.
- Currently you create a json-server structure via `main.js` you need create a REST API with JSON Server, please check this link: https://medium.com/codingthesmartway-com-blog/create-a-rest-api-with-json-server-36da8680136d
- You need to thoroughly understand the MVC pattern and do the work sequentially, that would be good approach for you.

Please double check, and let me know if you don’t clear, Thanks

**Comment by ngocquang2509** [comment]
I can't access to the link above. I think it related to proxy and firewall

**Comment by hungle-agilityio** [comment]
@ngocquang2509 Let's try using incognito window
